resources:
- name: concourse-deploy-bosh
  type: git
  check_every: 4h
  source:
    uri: https://github.com/s-matyukevich/concourse-deploy-bosh
    branch: master
- name: concourse-deploy-cloudfoundry
  type: git
  check_every: 4h
  source:
    uri: https://github.com/enaml-ops/concourse-deploy-cloudfoundry
    branch: master
- name: omg-cli
  type: github-release
  check_every: 4h
  source:
    user: s-matyukevich
    repository: omg-cli
- name: bosh-photon-cpi
  type: github-bosh-release
  check_every: 4h
  source:
    user: s-matyukevich
    repository: bosh-photon-cpi-release
- name: pcf-pipeline
  type: concourse-pipeline
  source:
    target: {{concourse-url}}
    insecure: "true"
    teams:
    - name: main
      username: {{concourse-user}}
      password: {{concourse-password}}

resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: robdimsdale/concourse-pipeline-resource
    tag: latest-final
- name: github-bosh-release
  type: docker-image
  source:
    repository: smatyukevich/github-bosh-release-resource

jobs:
- name: create-flavors
  plan:
    - aggregate:
      - get: concourse-deploy-bosh
    - task: create-flavors
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/create-flavors.sh
        params:
          PHOTON_URL: {{photon-url}}
          PHOTON_USER: {{photon-user}}
          PHOTON_PASSWORD: {{photon-password}}
          PHOTON_TENANT: {{photon-tenant}}
          PHOTON_PROJECT: {{photon-project}}
        inputs:
        - name: concourse-deploy-bosh
- name: deploy-bosh
  plan:
    - aggregate:
      - get: concourse-deploy-bosh
      - get: bosh-photon-cpi
      - get: omg-cli
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/deploy-bosh.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          PCF_MANAGEMENT_CIDR: {{pcf-management-cidr}}
          PCF_MANAGEMENT_GATEWAY: {{pcf-management-gateway}}
          PCF_MANAGEMENT_DNS: {{pcf-management-dns}}
          PCF_MANAGEMENT_PHOTON_ID: {{pcf-management-photon-id}}
          BOSH_IP: {{bosh-ip}}
          DEPLOYMENT_NAME: {{deployment-name}}
          PHOTON_URL: {{photon-url}}
          PHOTON_USER: {{photon-user}}
          PHOTON_PASSWORD: {{photon-password}}
          PHOTON_PROJECT_ID: {{photon-project-id}}
          NTP_SERVER: {{ntp-server}}
        inputs:
        - name: concourse-deploy-bosh
        - name: bosh-photon-cpi
        - name: omg-cli
- name: deploy-cloudconfig
  plan:
    - aggregate:
      - get: concourse-deploy-bosh
      - get: omg-cli
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/deploy-cloudconfig.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_IP: {{bosh-ip}}
          PCF_MANAGEMENT_CIDR: {{pcf-management-cidr}}
          PCF_MANAGEMENT_GATEWAY: {{pcf-management-gateway}}
          PCF_MANAGEMENT_DNS: {{pcf-management-dns}}
          PCF_MANAGEMENT_RESERVED: {{pcf-management-reserved}}
          PCF_MANAGEMENT_STATIC: {{pcf-management-static}}
          PCF_MANAGEMENT_PHOTON_ID: {{pcf-management-photon-id}}
          PCF_SERVICES_CIDR: {{pcf-services-cidr}}
          PCF_SERVICES_GATEWAY: {{pcf-services-gateway}}
          PCF_SERVICES_DNS: {{pcf-services-dns}}
          PCF_SERVICES_RESERVED: {{pcf-services-reserved}}
          PCF_SERVICES_STATIC: {{pcf-services-static}}
          PCF_SERVICES_PHOTON_ID: {{pcf-services-photon-id}}
          PCF_DEPLOYMENT_CIDR: {{pcf-deployment-cidr}}
          PCF_DEPLOYMENT_GATEWAY: {{pcf-deployment-gateway}}
          PCF_DEPLOYMENT_DNS: {{pcf-deployment-dns}}
          PCF_DEPLOYMENT_RESERVED: {{pcf-deployment-reserved}}
          PCF_DEPLOYMENT_STATIC: {{pcf-deployment-static}}
          PCF_DEPLOYMENT_PHOTON_ID: {{pcf-deployment-photon-id}}
        inputs:
        - name: concourse-deploy-bosh
        - name: omg-cli
- name: update-pcf-pipeline
  plan:
    - aggregate:
      - get: concourse-deploy-cloudfoundry
      - get: concourse-deploy-bosh
    - task: generate-cf-deployment-properties
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/generate-cf-deployment-properties.sh
        params:
          SYSTEM_DOMAIN: {{system-domain}}
          APP_DOMAIN: {{app-domain}}
          SYSLOG_ADDRESS: {{syslog-address}}
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_IP: {{bosh-ip}}
          CONCOURSE_URL: {{concourse-url}}
          CONCOURSE_USER: {{concourse-user}}
          CONCOURSE_PASSWORD: {{concourse-password}}
          DEPLOYMENT_NAME: {{deployment-name}}
          PRODUCT_SLUG: {{product-slug}}
          PRODUCT_VERSION: {{product-version}}
          PRODUCT_PLUGIN: {{product-version}}
          PIVNET_API_TOKEN: {{pivnet-api-token}}
          SKIP_HAPROXY: {{skip-haproxy}}
          HAPROXY_IP: {{haproxy-ip}}
          PCF_DEPLOYMENT_STATIC: {{pcf-deployment-static}}
          STEMCELL_CPI_GLOB: {{stemcell-cpi-glob}}
          STEMCELL_VERSION: {{stemcell-version}}
        inputs:
        - name: concourse-deploy-bosh
        outputs:
        - name: concourse
    - put: pcf-pipeline
      params:
        pipelines:
        - name: deploy-cf-{{deployment-name}}
          team: main
          config_file: concourse-deploy-cloudfoundry/pcf-pipeline.yml
          vars_files:
          - concourse/pcf-pipeline-vars.yml
      

      


      
