resources:

- name: concourse-deploy-bosh
  type: git
  source:
    uri: {{deploy-bosh-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-cloudfoundry
  type: git
  source:
    uri: {{deploy-cloudfoundry-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-redis
  type: git
  source:
    uri: {{deploy-redis-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-p-mysql
  type: git
  source:
    uri: {{deploy-p-mysql-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-turbulence
  type: git
  source:
    uri: {{deploy-turbulence-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-chaos-loris
  type: git
  source:
    uri: {{deploy-chaos-loris-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-rabbitmq
  type: git
  source:
    uri: {{deploy-rabbitmq-git-url}}
    private_key: {{git-private-key}}

- name: omg-cli
  type: github-release
  check_every: 4h
  source:
    user: s-matyukevich
    repository: omg-cli
- name: bosh-photon-cpi
  type: github-bosh-release
  check_every: 4h
  source:
    user: s-matyukevich
    repository: bosh-photon-cpi-release
- name: bosh-version
  type: concourse-version-resource

resource_types:
- name: github-bosh-release
  type: docker-image
  source:
    repository: smatyukevich/github-bosh-release-resource
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

jobs:
- name: deploy-bosh
  plan:
    - aggregate:
      - get: concourse-deploy-bosh
      - get: bosh-photon-cpi
      - get: omg-cli
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/deploy-bosh.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          PCF_MANAGEMENT_CIDR: {{pcf-management-cidr}}
          PCF_MANAGEMENT_GATEWAY: {{pcf-management-gateway}}
          PCF_MANAGEMENT_DNS: {{pcf-management-dns}}
          PCF_MANAGEMENT_PHOTON_ID: {{pcf-management-photon-id}}
          BOSH_IP: {{bosh-ip}}
          DEPLOYMENT_NAME: {{deployment-name}}
          PHOTON_URL: {{photon-url}}
          PHOTON_USER: {{photon-user}}
          PHOTON_PASSWORD: {{photon-password}}
          PHOTON_PROJECT_ID: {{photon-project-id}}
          NTP_SERVER: {{ntp-server}}
        inputs:
        - name: concourse-deploy-bosh
        - name: bosh-photon-cpi
        - name: omg-cli
    - put: bosh-version
- name: deploy-cloudconfig
  plan:
    - aggregate:
      - get: bosh-version
        trigger: true
        passed: [deploy-bosh]
      - get: concourse-deploy-bosh
      - get: omg-cli
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/deploy-cloudconfig.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_IP: {{bosh-ip}}
          PCF_MANAGEMENT_CIDR: {{pcf-management-cidr}}
          PCF_MANAGEMENT_GATEWAY: {{pcf-management-gateway}}
          PCF_MANAGEMENT_DNS: {{pcf-management-dns}}
          PCF_MANAGEMENT_RESERVED: {{pcf-management-reserved}}
          PCF_MANAGEMENT_STATIC: {{pcf-management-static}}
          PCF_MANAGEMENT_PHOTON_ID: {{pcf-management-photon-id}}
          PCF_SERVICES_CIDR: {{pcf-services-cidr}}
          PCF_SERVICES_GATEWAY: {{pcf-services-gateway}}
          PCF_SERVICES_DNS: {{pcf-services-dns}}
          PCF_SERVICES_RESERVED: {{pcf-services-reserved}}
          PCF_SERVICES_STATIC: {{pcf-services-static}}
          PCF_SERVICES_PHOTON_ID: {{pcf-services-photon-id}}
          PCF_DEPLOYMENT_CIDR: {{pcf-deployment-cidr}}
          PCF_DEPLOYMENT_GATEWAY: {{pcf-deployment-gateway}}
          PCF_DEPLOYMENT_DNS: {{pcf-deployment-dns}}
          PCF_DEPLOYMENT_RESERVED: {{pcf-deployment-reserved}}
          PCF_DEPLOYMENT_STATIC: {{pcf-deployment-static}}
          PCF_DEPLOYMENT_PHOTON_ID: {{pcf-deployment-photon-id}}
        inputs:
        - name: concourse-deploy-bosh
        - name: omg-cli
- name: update-pipelines
  plan:
    - aggregate:
      - get: bosh-version
        trigger: true
        passed: [deploy-cloudconfig]
      - get: concourse-deploy-cloudfoundry
      - get: concourse-deploy-bosh
      - get: concourse-deploy-redis
      - get: concourse-deploy-p-mysql
      - get: concourse-deploy-turbulence
      - get: concourse-deploy-chaos-loris
      - get: concourse-deploy-rabbitmq
    - task: update-pipelines
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-bosh/ci/tasks/update-pipelines.sh
        params:
          SYSTEM_DOMAIN: {{system-domain}}
          APP_DOMAIN: {{app-domain}}
          SYSLOG_ADDRESS: {{syslog-address}}
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_IP: {{bosh-ip}}
          CONCOURSE_URL: {{concourse-url}}
          CONCOURSE_USER: {{concourse-user}}
          CONCOURSE_PASSWORD: {{concourse-password}}
          DEPLOYMENT_NAME: {{deployment-name}}
          PRODUCT_SLUG: {{product-slug}}
          PRODUCT_VERSION: {{product-version}}
          PRODUCT_PLUGIN: {{product-plugin}}
          PIVNET_API_TOKEN: {{pivnet-api-token}}
          SKIP_HAPROXY: {{skip-haproxy}}
          HAPROXY_IP: {{haproxy-ip}}
          PCF_DEPLOYMENT_STATIC: {{pcf-deployment-static}}
          STEMCELL_CPI_GLOB: {{stemcell-cpi-glob}}
          STEMCELL_VERSION: {{stemcell-version}}
          PCF_DEPLOYMENT_CIDR: {{pcf-deployment-cidr}}
          UAA_LDAP_PASSWORD: {{uaa-ldap-password}}
          UAA_LDAP_URL: {{uaa-ldap-url}}
          UAA_LDAP_USER_DN: {{uaa-ldap-user-dn}}
          UAA_LDAP_SEARCH_BASE: {{uaa-ldap-search-base}}
          UAA_LDAP_SEARCH_FILTER: {{uaa-ldap-search-filter}}
          UAA_LADP_MAIL_ATTRIBUTENAME: {{uaa-ldap-mail-attributename}}
          DEPLOY_CLOUDFOUNDRY_GIT_URL: {{deploy-cloudfoundry-git-url}}
          DEPLOY_REDIS_GIT_URL: {{deploy-redis-git-url}}
          DEPLOY_P_MYSQL_GIT_URL: {{deploy-p-mysql-git-url}}
          DEPLOY_TURBULENCE_GIT_URL: {{deploy-turbulence-git-url}}
          DEPLOY_CHAOS_LORIS_GIT_URL: {{deploy-chaos-loris-git-url}}
          DEPLOY_RABBITMQ_GIT_URL: {{deploy-rabbitmq-git-url}}
          GIT_PRIVATE_KEY: {{git-private-key}}
        inputs:
        - name: concourse-deploy-bosh
        - name: concourse-deploy-cloudfoundry
        - name: concourse-deploy-redis
        - name: concourse-deploy-p-mysql
        - name: concourse-deploy-turbulence
        - name: concourse-deploy-chaos-loris
        - name: concourse-deploy-rabbitmq

      


      
